pragma Singleton
import QtQuick

// ─────────────────────────────────────────────────────────────────────────────
// Theme — auto-generated by wallpaper-set.sh
// Wallpaper: /home/sassech/Imágenes/k-On Wallpaper/wallpaperflare.com_wallpaper (16).jpg
// Re-run  ~/.config/quickshell/scripts/wallpaper-set.sh  to update.
// ─────────────────────────────────────────────────────────────────────────────
QtObject {

    // ── Wallpaper-derived (Material You dark scheme) ──────────────────────
    readonly property color _bg:          "#0E1415"   // base color — internal use only
    readonly property color surface1:     "#171D1E"
    readonly property color surface2:     "#1B2122"
    readonly property color surface3:     "#252B2C"
    readonly property color surface4:     "#303637"
    readonly property color overlay:      "#343A3B"
    readonly property color muted3:       "#3F484A"
    readonly property color muted2:       "#899294"
    readonly property color muted1:       "#BEC8CA"
    readonly property color text:         "#DEE4E4"
    readonly property color accent:       "#81D3DE"
    readonly property color accentDim:    "#004F56"
    readonly property color accent2:      "#B1CBCF"

    // ── Semantic (also wallpaper-aware) ───────────────────────────────────
    readonly property color error:        "#FFB4AB"
    readonly property color warning:      "#B9C6EA"
    readonly property color yellow:       "#F9D492"   // no M3 equivalent — fixed
    readonly property color success:      "#8BD4A4"   // no M3 equivalent — fixed
    readonly property color sky:          "#88C9D4"   // no M3 equivalent — fixed

    // ── Computed alpha variants (auto-update from above) ──────────────────
    readonly property color dim:            Qt.rgba(_bg.r, _bg.g, _bg.b, 0.80)
    readonly property color cardBg:         Qt.rgba(_bg.r, _bg.g, _bg.b, 0.91)
    readonly property color cardBg2:        Qt.rgba(_bg.r, _bg.g, _bg.b, 0.60)
    readonly property color cardBg3:        Qt.rgba(_bg.r, _bg.g, _bg.b, 0.97)
    readonly property color scrim:          Qt.rgba(0, 0, 0, 0.55)
    readonly property color accentSurface:  Qt.tint(surface2, Qt.rgba(accent.r,  accent.g,  accent.b,  0.22))
    readonly property color successSurface: Qt.tint(surface2, Qt.rgba(success.r, success.g, success.b, 0.22))
    readonly property color hover:          Qt.rgba(1, 1, 1, 0.08)
    readonly property color hover2:         Qt.rgba(1, 1, 1, 0.20)
}
