pragma Singleton
import QtQuick

// ─────────────────────────────────────────────────────────────────────────────
// Theme — auto-generated by wallpaper-set.sh
// Wallpaper: /home/sassech/Imágenes/k-On Wallpaper/wallpaperflare.com_wallpaper (16).jpg
// Re-run  ~/.config/quickshell/scripts/wallpaper-set.sh  to update.
// ─────────────────────────────────────────────────────────────────────────────
QtObject {

    // ── Wallpaper-derived (Material You dark scheme) ──────────────────────
    readonly property color base:         "#0E1416"
    readonly property color surface1:     "#171D1E"
    readonly property color surface2:     "#1B2122"
    readonly property color surface3:     "#252B2C"
    readonly property color surface4:     "#303637"
    readonly property color overlay:      "#343A3C"
    readonly property color muted3:       "#3F484A"
    readonly property color muted2:       "#899295"
    readonly property color muted1:       "#BFC8CB"
    readonly property color text:         "#DEE3E5"
    readonly property color accent:       "#83D2E3"
    readonly property color accentDim:    "#004E5A"
    readonly property color accent2:      "#B1CBD1"

    // ── Semantic (also wallpaper-aware) ───────────────────────────────────
    readonly property color error:        "#FFB4AB"
    readonly property color warning:      "#BCC5EB"
    readonly property color yellow:       "#F9D492"   // no M3 equivalent — fixed
    readonly property color success:      "#8BD4A4"   // no M3 equivalent — fixed
    readonly property color sky:          "#88C9D4"   // no M3 equivalent — fixed

    // ── Computed alpha variants (auto-update from above) ──────────────────
    readonly property color dim:            Qt.rgba(base.r, base.g, base.b, 0.80)
    readonly property color cardBg:         Qt.rgba(base.r, base.g, base.b, 0.91)
    readonly property color cardBg2:        Qt.rgba(base.r, base.g, base.b, 0.60)
    readonly property color cardBg3:        Qt.rgba(base.r, base.g, base.b, 0.97)  // modales muy opacos
    readonly property color scrim:          Qt.rgba(0, 0, 0, 0.55)                  // overlay oscuro estándar
    readonly property color accentSurface:  Qt.tint(surface2, Qt.rgba(accent.r,  accent.g,  accent.b,  0.22))
    readonly property color successSurface: Qt.tint(surface2, Qt.rgba(success.r, success.g, success.b, 0.22))
    readonly property color hover:          Qt.rgba(1, 1, 1, 0.08)
    readonly property color hover2:         Qt.rgba(1, 1, 1, 0.20)
}
