exec-once = lxpolkit &

exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user start hyprland-session.target
exec-once = bash -c "wl-paste --watch cliphist store &"
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

#clipboard manager
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

#swww daemon + restore wallpaper
exec-once = swww-daemon --no-cache
exec-once = bash -c 'for i in $(seq 1 20); do swww query &>/dev/null && break; sleep 0.3; done; WP=$(cat ~/.config/quickshell/config/current-wallpaper 2>/dev/null | tr -d "\n") && [ -f "$WP" ] && ~/.config/quickshell/scripts/wallpaper-set.sh "$WP"'

#bluetooth off by default
exec-once = bluetoothctl power off

#quickshell
exec-once = quickshell &
