#!/usr/bin/env python3
"""
Runs matugen on the current wallpaper, parses the Material You dark palette,
and regenerates Components/Theme.qml with the new colors.
Called by wallpaper-set.sh.
"""
import os
import subprocess
import sys
import re

if len(sys.argv) < 3:
    print("Usage: parse-matugen.py <wallpaper> <output-theme.qml>")
    sys.exit(1)

WALLPAPER = sys.argv[1]
OUTPUT = sys.argv[2]

try:
    result = subprocess.run(
        ["matugen", "-m", "dark", "image", WALLPAPER,
         "--prefer", "saturation", "--dry-run", "--show-colors"],
        capture_output=True, text=True,
        timeout=30,  # evita que matugen cuelgue indefinidamente
    )
except subprocess.TimeoutExpired:
    print("ERROR: matugen tardó más de 30s, abortando.", file=sys.stderr)
    sys.exit(1)

raw = result.stdout + result.stderr

# Parse the unicode box-drawing table: each row looks like
#   │ name              │ #LIGHT │  │ #DARK  │  │
colors = {}
for line in raw.split("\n"):
    parts = line.split("│")
    if len(parts) >= 5:
        name = parts[1].strip()
        dark = parts[4].strip()
        dark = dark.split()[0] if dark else ""
        if re.match(r"^#[0-9A-Fa-f]{6}$", dark) and name:
            colors[name] = dark.upper()

if not colors:
    print("ERROR: No colors parsed from matugen output.", file=sys.stderr)
    print("Raw output:", raw[:400], file=sys.stderr)
    sys.exit(1)


def c(key, fallback):
    return colors.get(key, fallback)


theme = f"""pragma Singleton
import QtQuick

// ─────────────────────────────────────────────────────────────────────────────
// Theme — auto-generated by wallpaper-set.sh
// Wallpaper: {WALLPAPER}
// Re-run  ~/.config/quickshell/scripts/wallpaper-set.sh  to update.
// ─────────────────────────────────────────────────────────────────────────────
QtObject {{

    // ── Wallpaper-derived (Material You dark scheme) ──────────────────────
    readonly property color _bg:          "{c('surface_dim',               '#141318')}"   // base color — internal use only
    readonly property color surface1:     "{c('surface_container_low',     '#1C1B20')}"
    readonly property color surface2:     "{c('surface_container',         '#201F24')}"
    readonly property color surface3:     "{c('surface_container_high',    '#2B292F')}"
    readonly property color surface4:     "{c('surface_container_highest', '#36343A')}"
    readonly property color overlay:      "{c('surface_bright',            '#3A383E')}"
    readonly property color muted3:       "{c('outline_variant',           '#48454E')}"
    readonly property color muted2:       "{c('outline',                   '#938F99')}"
    readonly property color muted1:       "{c('on_surface_variant',        '#CAC4CF')}"
    readonly property color text:         "{c('on_surface',                '#E6E1E9')}"
    readonly property color accent:       "{c('primary',                   '#CDBDFF')}"
    readonly property color accentDim:    "{c('primary_container',         '#4B3E76')}"
    readonly property color accent2:      "{c('secondary',                 '#CBC3DC')}"

    // ── Semantic (also wallpaper-aware) ───────────────────────────────────
    readonly property color error:        "{c('error',                     '#FFB4AB')}"
    readonly property color warning:      "{c('tertiary',                  '#EEB8CA')}"
    readonly property color yellow:       "#F9D492"   // no M3 equivalent — fixed
    readonly property color success:      "#8BD4A4"   // no M3 equivalent — fixed
    readonly property color sky:          "#88C9D4"   // no M3 equivalent — fixed
    readonly property color blue:         "#82AAFF"   // no M3 equivalent — fixed (PowerSaver)
    readonly property color purple:       "#C4B5FD"   // no M3 equivalent — fixed (Log out)

    // ── Computed alpha variants (auto-update from above) ──────────────────
    readonly property color dim:            Qt.rgba(_bg.r, _bg.g, _bg.b, 0.80)
    readonly property color cardBg:         Qt.rgba(_bg.r, _bg.g, _bg.b, 0.91)
    readonly property color cardBg2:        Qt.rgba(_bg.r, _bg.g, _bg.b, 0.60)
    readonly property color cardBg3:        Qt.rgba(_bg.r, _bg.g, _bg.b, 0.97)
    readonly property color scrim:          Qt.rgba(0, 0, 0, 0.55)
    readonly property color accentSurface:  Qt.tint(surface2, Qt.rgba(accent.r,  accent.g,  accent.b,  0.22))
    readonly property color successSurface: Qt.tint(surface2, Qt.rgba(success.r, success.g, success.b, 0.22))
    readonly property color hover:          Qt.rgba(1, 1, 1, 0.08)
    readonly property color hover2:         Qt.rgba(1, 1, 1, 0.20)
    readonly property color surfaceHover:   Qt.rgba(1, 1, 1, 0.08)   // alias for hover — used by TrayIcon hover state
    readonly property color borderSubtle:   Qt.rgba(1, 1, 1, 0.12)   // subtle border — used by TrayIcon tooltip
}}
"""

# Write atómico: escribir a .tmp y mover — Theme.qml nunca queda corrupto
_tmp = OUTPUT + ".tmp"
try:
    with open(_tmp, "w") as f:
        f.write(theme)
    os.replace(_tmp, OUTPUT)  # atómico en POSIX
except Exception as e:
    # Limpiar .tmp si quedó
    try:
        os.unlink(_tmp)
    except OSError:
        pass
    print(f"ERROR: No se pudo escribir {OUTPUT}: {e}", file=sys.stderr)
    sys.exit(1)

print(f"Theme.qml written ({len(colors)} colors extracted)")

# ── Optional: regenerate hyprlock.conf ────────────────────────────────────────
if len(sys.argv) >= 4:
    HYPRLOCK = sys.argv[3]

    def rgba(hex_color, alpha="FF"):
        h = hex_color.lstrip("#")
        return f"rgba({h}{alpha})"

    _base = c('surface_dim',               '#11140E')
    _surf2 = c('surface_container',         '#1D211A')
    _accent = c('primary',                   '#ABD28F')
    _success = '#8BD4A4'
    _warning = c('tertiary',                  '#A0CFCF')
    _error = c('error',                     '#FFB4AB')
    _text = c('on_surface',                '#E1E4D9')
    _muted1 = c('on_surface_variant',        '#C4C8BB')
    _muted2 = c('outline',                   '#8E9286')
    _yellow = '#F9D492'

    hyprlock = f"""# hyprlock.conf — auto-generated by wallpaper-set.sh
# Do not edit manually; re-run wallpaper-set.sh to update.

$font      = JetBrainsMono Nerd Font
$font_mono = JetBrainsMono Nerd Font

general {{
    hide_cursor        = true
    grace              = 0
    ignore_empty_input = false
}}

animations {{
    enabled = true
    bezier  = easeOut, 0.16, 1, 0.3, 1
    bezier  = easeIn,  0.7,  0, 0.84, 0
    animation = fadeIn,          1, 4, easeOut
    animation = fadeOut,         1, 4, easeIn
    animation = inputFieldDots,  1, 2, easeOut
    animation = inputFieldWidth, 1, 3, easeOut
    animation = inputFieldFade,  1, 3, easeOut
}}

# ── Background ────────────────────────────────────────────────────────────────
background {{
    monitor     =
    path        = screenshot
    blur_passes = 3
    blur_size   = 7
    brightness  = 0.65
    vibrancy    = 0.15
    contrast    = 0.85
}}

# ── Clock ─────────────────────────────────────────────────────────────────────
label {{
    monitor     =
    text        = $TIME
    font_size   = 88
    font_family = $font

    color         = {rgba(_text)}
    shadow_passes = 2
    shadow_size   = 6
    shadow_color  = {rgba(_base, 'CC')}

    position = 0, 200
    halign   = center
    valign   = center
}}

# ── Date ──────────────────────────────────────────────────────────────────────
label {{
    monitor     =
    text        = cmd[update:60000] date +"  %A, %d %B %Y"
    font_size   = 18
    font_family = $font

    color         = {rgba(_muted1, 'DD')}
    shadow_passes = 1
    shadow_size   = 4
    shadow_color  = {rgba(_base, 'CC')}

    position = 0, 120
    halign   = center
    valign   = center
}}

# ── Input field ───────────────────────────────────────────────────────────────
input-field {{
    monitor =
    size    = 340, 52

    outline_thickness = 2
    rounding          = 12

    inner_color = {rgba(_surf2, 'CC')}
    outer_color = {rgba(_accent, 'CC')}
    check_color = {rgba(_success)} {rgba(_accent)} 45deg
    fail_color  = {rgba(_error)} {rgba(_warning)} 40deg

    font_color    = {rgba(_text)}
    font_family   = $font_mono
    fade_on_empty = true
    fade_timeout  = 2000

    placeholder_text = <span foreground="#{_muted2}">  Contraseña</span>
    fail_text        = <span foreground="#{_error}">✗  $PAMFAIL</span>

    dots_spacing  = 0.35
    dots_center   = true
    dots_rounding = -1

    capslock_color = {rgba(_yellow)}

    position = 0, -20
    halign   = center
    valign   = center
}}

# ── Hint ──────────────────────────────────────────────────────────────────────
label {{
    monitor     =
    text        = ESC · Ctrl+U para limpiar
    font_size   = 11
    font_family = $font

    color    = {rgba(_muted2, '88')}
    position = 0, -90
    halign   = center
    valign   = center
}}
"""

    _tmp_hl = HYPRLOCK + ".tmp"
    try:
        with open(_tmp_hl, "w") as f:
            f.write(hyprlock)
        os.replace(_tmp_hl, HYPRLOCK)
    except Exception as e:
        try:
            os.unlink(_tmp_hl)
        except OSError:
            pass
        print(f"ERROR: No se pudo escribir {HYPRLOCK}: {e}", file=sys.stderr)
        sys.exit(1)
    print("hyprlock.conf written")
